### ISSUE TITLE
missing semicolon

### ISSUE THREAD

**Issue by EternalCode** [pret/pokeruby#139]
https://github.com/pret/pokeruby/blob/master/charmap.txt

The semi colon is not contained. I believe this would be 036.

**Comment by YamaArashi** [comment]
It's not included because it's not in version 1.0 of the game. All of the additions from 1.1 need to be added.

**Comment by camthesaxman** [comment]
This has been resolved. The repository builds versions 1.0, 1.1, and 1.2.

**Comment by drifloony** [comment]
@EternalCode seems to have been referring to the charmap.txt file. In revision 1, several characters were added for compatibility with the European editions of the game. However, these characters were still not used in the English edition, so revision 1 and 2 still build even though the new characters are missing from the charmap.txt file.

https://tcrf.net/Pok%C3%A9mon_Ruby_and_Sapphire/Regional_Differences#Font_Differences_2
